<a href="https://colab.research.google.com/github/Whitehat-1711/DL_Tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this course I am going to learn how to use tensorflow from very basic level
Topics covered are:
* Intro to tensors   
* manipulating tensors
* Tensors n Numpy
* Using tf.fit()
* Using GPU's with TF (or TPU)





##Intro to tensors

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim


1

In [ ]:
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:

another_matrix = tf.constant([[10., 7.],
                              [2., 9.],
                              [3.,4.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 2.,  9.],
       [ 3.,  4.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
 # Let's create a tensor
 tensor = tf.constant([[[1,2,3],
                        [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
 tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've done so far:

* Scalar: a single number.
* Vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: a n-dim array of numbers

###Creating tensors with tf.Variable

In [ ]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Let's try to change one of the elements in our changable tensor
#changable_tensor[0] = 7
#changable_tensor

In [ ]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating Random Tensors
Random tensors are tensors of some arbitary size which contains random numbers.

In [ ]:
#create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Schuffle the order of elements in a tensor

In [ ]:
#schuffle the order of tensor (Can be used when I want to shuffle my data so the inherent order dosen't affect me)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
#shuffle our tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

🛠️ **EXERCISE** : Read through Tensorflow documentation on random seed generator:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed
and practice writing 5 tensors and shuffling them.

It looks like if we want our shuffled tensors to be in same order, we have to use global level as well as operational level random seeds:

> Rule 4:If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.


In [ ]:
tnsr_1 = tf.constant([[52, 11, 44],
                      [25, 66, 23],
                      [98, 87, 88],
                      [131,22,55],
                      [1092, 939, 828]])
print(tnsr_1)
tf.random.set_seed(23)
tf.random.shuffle(tnsr_1)


tf.Tensor(
[[  52   11   44]
 [  25   66   23]
 [  98   87   88]
 [ 131   22   55]
 [1092  939  828]], shape=(5, 3), dtype=int32)


<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[  98,   87,   88],
       [  52,   11,   44],
       [  25,   66,   23],
       [1092,  939,  828],
       [ 131,   22,   55]], dtype=int32)>

### Other ways to make tensors

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape = (3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

###Turn Numpy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numberical calculations).

In [ ]:
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)
# X = tf.constant(some_matrix) #capital for matrix or tensor
# y = tf.constant(vector) #non-capital for vector

In [ ]:
A = tf.constant(numpy_A, shape= (2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
#practice block
arr1 = np.arange(1,101, dtype = np.int32)
ten_1 = tf.constant(arr1, shape =(25,4))
tf.random.shuffle(ten_1), ten_1.ndim

(<tf.Tensor: shape=(25, 4), dtype=int32, numpy=
 array([[ 13,  14,  15,  16],
        [ 69,  70,  71,  72],
        [  9,  10,  11,  12],
        [ 57,  58,  59,  60],
        [ 85,  86,  87,  88],
        [ 49,  50,  51,  52],
        [ 33,  34,  35,  36],
        [ 73,  74,  75,  76],
        [  5,   6,   7,   8],
        [ 37,  38,  39,  40],
        [ 61,  62,  63,  64],
        [ 17,  18,  19,  20],
        [  1,   2,   3,   4],
        [ 29,  30,  31,  32],
        [ 65,  66,  67,  68],
        [ 93,  94,  95,  96],
        [ 21,  22,  23,  24],
        [ 97,  98,  99, 100],
        [ 81,  82,  83,  84],
        [ 25,  26,  27,  28],
        [ 53,  54,  55,  56],
        [ 77,  78,  79,  80],
        [ 89,  90,  91,  92],
        [ 41,  42,  43,  44],
        [ 45,  46,  47,  48]], dtype=int32)>,
 2)

### Getting informations from tensors

* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Creating a rank 4 tensor
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor, rank_4_tensor.ndim

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>,
 4)

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#Get various attributes of our tensor
print("Datatype of every element", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("The shape of the tensor is", rank_4_tensor.shape)
print("Elements along the 0 axis is:",rank_4_tensor.shape[0])
print("Element along the last axis is:", rank_4_tensor.shape[-1])

Datatype of every element <dtype: 'float32'>
Number of dimensions (rank): 4
The shape of the tensor is (2, 3, 4, 5)
Elements along the 0 axis is: 2
Element along the last axis is: 5


### Indexing tensors
Tensors can be indexed just like python course

In [ ]:
list = [1,2,3,4,5,6,7,8,9]
list[2:-2]

[3, 4, 5, 6, 7]

In [ ]:
list[:1]

[1]

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first elements from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimension)
rank_2_tensor = tf.constant([[10, 7],
                            [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#Getting last item of rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
#Adding an extra axis to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Another way to increase the dimension
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [ ]:
print(rank_2_tensor.shape[0])

2


In [ ]:
#practice blocks
tensor_x = tf.constant([
    [
        [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]],
         [[21, 22, 23, 24, 25], [26, 27, 28, 29, 30], [31, 32, 33, 34, 35], [36, 37, 38, 39, 40]],
         [[41, 42, 43, 44, 45], [46, 47, 48, 49, 50], [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]]],
        [[[61, 62, 63, 64, 65], [66, 67, 68, 69, 70], [71, 72, 73, 74, 75], [76, 77, 78, 79, 80]],
         [[81, 82, 83, 84, 85], [86, 87, 88, 89, 90], [91, 92, 93, 94, 95], [96, 97, 98, 99, 100]],
         [[101, 102, 103, 104, 105], [106, 107, 108, 109, 110], [111, 112, 113, 114, 115], [116, 117, 118, 119, 120]]]
    ],
    [
        [[[121, 122, 123, 124, 125], [126, 127, 128, 129, 130], [131, 132, 133, 134, 135], [136, 137, 138, 139, 140]],
         [[141, 142, 143, 144, 145], [146, 147, 148, 149, 150], [151, 152, 153, 154, 155], [156, 157, 158, 159, 160]],
         [[161, 162, 163, 164, 165], [166, 167, 168, 169, 170], [171, 172, 173, 174, 175], [176, 177, 178, 179, 180]]],
        [[[181, 182, 183, 184, 185], [186, 187, 188, 189, 190], [191, 192, 193, 194, 195], [196, 197, 198, 199, 200]],
         [[201, 202, 203, 204, 205], [206, 207, 208, 209, 210], [211, 212, 213, 214, 215], [216, 217, 218, 219, 220]],
         [[221, 222, 223, 224, 225], [226, 227, 228, 229, 230], [231, 232, 233, 234, 235], [236, 237, 238, 239, 240]]]
    ],
    [
        [[[241, 242, 243, 244, 245], [246, 247, 248, 249, 250], [251, 252, 253, 254, 255], [256, 257, 258, 259, 260]],
         [[261, 262, 263, 264, 265], [266, 267, 268, 269, 270], [271, 272, 273, 274, 275], [276, 277, 278, 279, 280]],
         [[281, 282, 283, 284, 285], [286, 287, 288, 289, 290], [291, 292, 293, 294, 295], [296, 297, 298, 299, 300]]],
        [[[301, 302, 303, 304, 305], [306, 307, 308, 309, 310], [311, 312, 313, 314, 315], [316, 317, 318, 319, 320]],
         [[321, 322, 323, 324, 325], [326, 327, 328, 329, 330], [331, 332, 333, 334, 335], [336, 337, 338, 339, 340]],
         [[341, 342, 343, 344, 345], [346, 347, 348, 349, 350], [351, 352, 353, 354, 355], [356, 357, 358, 359, 360]]]
    ],
    [
        [[[361, 362, 363, 364, 365], [366, 367, 368, 369, 370], [371, 372, 373, 374, 375], [376, 377, 378, 379, 380]],
         [[381, 382, 383, 384, 385], [386, 387, 388, 389, 390], [391, 392, 393, 394, 395], [396, 397, 398, 399, 400]],
         [[401, 402, 403, 404, 405], [406, 407, 408, 409, 410], [411, 412, 413, 414, 415], [416, 417, 418, 419, 420]]],
        [[[421, 422, 423, 424, 425], [426, 427, 428, 429, 430], [431, 432, 433, 434, 435], [436, 437, 438, 439, 440]],
         [[441, 442, 443, 444, 445], [446, 447, 448, 449, 450], [451, 452, 453, 454, 455], [456, 457, 458, 459, 460]],
         [[461, 462, 463, 464, 465], [466, 467, 468, 469, 470], [471, 472, 473, 474, 475], [476, 477, 478, 479, 480]]]
    ],
    [
        [[[481, 482, 483, 484, 485], [486, 487, 488, 489, 490], [491, 492, 493, 494, 495], [496, 497, 498, 499, 500]],
         [[501, 502, 503, 504, 505], [506, 507, 508, 509, 510], [511, 512, 513, 514, 515], [516, 517, 518, 519, 520]],
         [[521, 522, 523, 524, 525], [526, 527, 528, 529, 530], [531, 532, 533, 534, 535], [536, 537, 538, 539, 540]]],
        [[[541, 542, 543, 544, 545], [546, 547, 548, 549, 550], [551, 552, 553, 554, 555], [556, 557, 558, 559, 560]],
         [[561, 562, 563, 564, 565], [566, 567, 568, 569, 570], [571, 572, 573, 574, 575], [576, 577, 578, 579, 580]],
         [[581, 582, 583, 584, 585], [586, 587, 588, 589, 590], [591, 592, 593, 594, 595], [596, 597, 598, 599, 600]]]
    ]
], dtype = tf.float32)
tensor_x

<tf.Tensor: shape=(5, 2, 3, 4, 5), dtype=float32, numpy=
array([[[[[  1.,   2.,   3.,   4.,   5.],
          [  6.,   7.,   8.,   9.,  10.],
          [ 11.,  12.,  13.,  14.,  15.],
          [ 16.,  17.,  18.,  19.,  20.]],

         [[ 21.,  22.,  23.,  24.,  25.],
          [ 26.,  27.,  28.,  29.,  30.],
          [ 31.,  32.,  33.,  34.,  35.],
          [ 36.,  37.,  38.,  39.,  40.]],

         [[ 41.,  42.,  43.,  44.,  45.],
          [ 46.,  47.,  48.,  49.,  50.],
          [ 51.,  52.,  53.,  54.,  55.],
          [ 56.,  57.,  58.,  59.,  60.]]],


        [[[ 61.,  62.,  63.,  64.,  65.],
          [ 66.,  67.,  68.,  69.,  70.],
          [ 71.,  72.,  73.,  74.,  75.],
          [ 76.,  77.,  78.,  79.,  80.]],

         [[ 81.,  82.,  83.,  84.,  85.],
          [ 86.,  87.,  88.,  89.,  90.],
          [ 91.,  92.,  93.,  94.,  95.],
          [ 96.,  97.,  98.,  99., 100.]],

         [[101., 102., 103., 104., 105.],
          [106., 107., 108., 109., 110.],
       

In [ ]:
print(tensor_x.shape)
print(tensor_x.dtype)
print(tensor_x.ndim)

(5, 2, 3, 4, 5)
<dtype: 'float32'>
5


### Manipulating tensor (tensor operations)

**Basic Operations**


In [ ]:
tensor = tf.constant([[10, 7],
                     [14, 9]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [24, 19]], dtype=int32)>

In [ ]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [140,  90]], dtype=int32)>

In [ ]:
tensor % 9

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 7],
       [5, 0]], dtype=int32)>

In [ ]:
#Faster way of computing (using tf functions for basic operations)
tf.add(tensor, 10)
tf.multiply(tensor, 9)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 90,  63],
       [126,  81]], dtype=int32)>

**Matrix Multiplication**

tf.linalg.matmul()

In [ ]:
tensor
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[198, 133],
       [266, 179]], dtype=int32)>

In [ ]:
# Matrix Multiplications with python operator "@"
tensor @tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[198, 133],
       [266, 179]], dtype=int32)>

In [ ]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[4, 5, 9],
                 [3, 9, 10]])
Z = tf.constant([[10, 11],
                 [12, 13],
                 [14, 15]])
tf.matmul(tf.reshape(Z, shape = (2,3)), X)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[103, 136],
       [130, 172]], dtype=int32)>

In [ ]:
#can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape = (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

**The Dot Product**

Matrix Multiplication is also refered to as the dot product.

You can perform the matrix multiplication using:
 * `tf.matmul()`
 * `tf.tensordot()`

In [ ]:
#Perform the dot product on X or Y
tf.tensordot(tf.transpose(X), Z, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[116, 125],
       [152, 164]], dtype=int32)>

In [ ]:
tf.matmul(Z, tf.transpose(X))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 32,  74, 116],
       [ 38,  88, 138],
       [ 44, 102, 160]], dtype=int32)>

### Changing the Datatype

In [ ]:
#Create a new tensor with float 32
B = tf.constant([1.24, 34.12])
B.dtype

tf.float32

In [ ]:
A = tf.constant([10, 7])
A.dtype

tf.int32

In [ ]:
#Change frm float32 to float16 (reduced accuracy)
C = tf.cast(B, dtype = tf.float16)
C

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 1.24, 34.12], dtype=float16)>

In [ ]:
#Change from int32 to float 32
D = tf.cast(B, dtype = tf.float16)
D


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 1.24, 34.12], dtype=float16)>

###Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values


In [ ]:
#getting the abosolute values
D = tf.constant([-7, -10])
tf.abs(D)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

**Other ways of aggregation:**

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of the tensor

In [ ]:
E = tf.constant(np.random.randint(0, 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([78, 80, 11, 86, 95, 57, 65,  3, 10, 10, 85, 92, 75, 91, 37, 95, 98,
        2,  3,  2, 86, 79, 74, 82, 56, 65, 18,  8, 26, 87, 49, 68, 10, 32,
        8, 48,  1, 96, 68,  1,  2, 49, 93, 17, 50, 92, 80, 86, 42, 58])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#finding the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
#finding the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2606>

**EXE: Find VARIENCE and STD. DEVIATION**

In [ ]:
tf.math.reduce_variance(E) # for this we require the tfp package.

TypeError: Input must be either real or complex. Received integer type <dtype: 'int64'>.

In [ ]:
#For statistical tools we need to import the tensorflow_probability package
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1158>

In [ ]:
# find standered deviation of E
E = tf.cast(E, dtype = tf.float32)
tfp.stats.stddev(E) # also tf.math.reduce_std(E) can be used

<tf.Tensor: shape=(), dtype=float32, numpy=34.03389>

###Find the positional maximum and minimum of a tensor

In [ ]:
#Create a new tensor for finding maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the maximum value of F
tf.reduce_max(F)


<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(F) == F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-Hot Encoding Tensors

In [ ]:
some_list = [0, 1, 2, 3]

#one hot encode our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
some_other_list = [0,1,2,3,4,5,6]
tf.one_hot(some_list, depth = 7)

<tf.Tensor: shape=(4, 7), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth = 5, on_value = 4, off_value = 5)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[4, 5, 5, 5, 5],
       [5, 4, 5, 5, 5],
       [5, 5, 4, 5, 5],
       [5, 5, 5, 4, 5]], dtype=int32)>

### squaring, log, square_root

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H ,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

TensorFlow interacts beautifully with Numpy



In [ ]:
#Create a tensor directly from a numpy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
type(np.array(J))

numpy.ndarray

In [ ]:
## IMPORTANT!!!!
numpy_J = tf.constant(np.array([10., 27., 38., 44.]))
tensor_J = tf.constant([2. ,4., 88., 82., 11.])
#checking datatype of each
numpy_J.dtype, tensor_J.dtype # numpy has the float64 data type!

(tf.float64, tf.float32)

### FINDING ACCESS TO GPUs

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sun Jun  2 07:04:00 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P0              27W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

**NOTE:** If you have access to a CUDA-enabled GPU, TF will automatically use it whenever possible

### EXERCISE.